css_code = (
    "@charset 'UTF-8';\n\n"
    ":root {\n"
    "  --primary-container: #111d15;\n"
    "  --on-primary-container: #779682;\n"
    "  --secondary-fixed: #39e5b8;\n"
    "  --secondary-glow: rgba(57, 229, 184, 0.25);\n"
    "  --on-secondary-fixed: #002b21;\n"
    "  --surface-lowest: #ffffff;\n"
    "  --surface-low: #eaeeec; /* 加深一点基础灰度 */\n"
    "  --surface-high: #dee5e1;\n"
    "  --on-surface: #141716;\n"
    "  --on-surface-variant: #4a524e;\n"
    "  --outline: #89938d;\n"
    "  --outline-variant: #b8c2bc; /* 加深边框线 */\n"
    "  --danger: #d93829;\n"
    "  --danger-glow: rgba(217, 56, 41, 0.2);\n"
    "  --font-headline: 'Space Grotesk', 'Source Han Sans SC', sans-serif;\n"
    "  --font-body: 'Inter', 'Source Han Sans SC', sans-serif;\n"
    "}\n\n"
    "* { box-sizing: border-box; margin: 0; padding: 0; border-radius: 0 !important; }\n\n"
    "html, body { min-height: 100%; color-scheme: light; }\n"
    "body { font-family: var(--font-body); color: var(--on-surface); background-color: var(--surface-low); overflow-x: hidden; position: relative; }\n\n"
    "/* The Grid */\n"
    "body::before { content: ''; position: fixed; inset: 0; pointer-events: none; background-image: linear-gradient(var(--outline-variant) 1px, transparent 1px), linear-gradient(90deg, var(--outline-variant) 1px, transparent 1px); background-size: 32px 32px; opacity: 0.15; z-index: -1; }\n"
    "body::after { content: ''; position: fixed; inset: 0; pointer-events: none; background: radial-gradient(circle at 100% 0%, rgba(255,255,255,0.9) 0%, transparent 60%), radial-gradient(circle at 30% 100%, rgba(57, 229, 184, 0.05) 0%, transparent 50%); z-index: -1; }\n\n"
    ".app { display: grid; grid-template-columns: 280px minmax(0, 1fr); min-height: 100vh; }\n\n"
    "/* SIDEBAR */\n"
    ".side { background: linear-gradient(180deg, #0a110c 0%, var(--primary-container) 100%); color: var(--surface-lowest); display: flex; flex-direction: column; position: relative; z-index: 20; padding: 0 0 24px 0; box-shadow: 4px 0 24px rgba(0,0,0,0.15); border-right: 1px solid rgba(57,229,184,0.1); }\n"
    ".side-top-dec { display: flex; align-items: center; gap: 8px; padding: 16px 24px; border-bottom: 1px solid rgba(255,255,255,0.05); font-family: var(--font-headline); font-size: 9px; color: var(--on-primary-container); letter-spacing: 2px; }\n"
    ".blink-dot { width: 6px; height: 6px; background: var(--secondary-fixed); box-shadow: 0 0 8px var(--secondary-fixed); animation: pulse 2s infinite; }\n"
    "@keyframes pulse { 0% { opacity: 1; } 50% { opacity: 0.3; } 100% { opacity: 1; } }\n"
    ".side-bottom-dec { margin-top: 16px; padding: 0 24px; font-family: var(--font-headline); font-size: 9px; color: rgba(255,255,255,0.15); letter-spacing: 2px; }\n"
    ".side-edge { position: absolute; right: 0; top: 0; bottom: 0; width: 2px; background: linear-gradient(180deg, transparent, var(--secondary-fixed), transparent); opacity: 0.4; }\n"
    ".block { border: none; background: transparent; padding: 0 24px; margin-top: 32px; box-shadow: none; }\n"
    ".brand .mini { font-family: var(--font-headline); color: var(--secondary-fixed); letter-spacing: 2px; font-size: 10px; margin-bottom: 12px; font-weight: 700; text-shadow: 0 0 8px rgba(57,229,184,0.3); }\n"
    "/* 这里是大字体的调整 */\n"
    ".brand .big { font-family: var(--font-headline); font-size: 56px; font-weight: 900; line-height: 0.85; text-transform: uppercase; color: #ffffff; letter-spacing: -3px; text-shadow: 0 4px 12px rgba(0,0,0,0.5); }\n"
    ".brand .row { display: flex; gap: 8px; margin-top: 20px; }\n"
    ".chip { background: rgba(57, 229, 184, 0.1); border: 1px solid rgba(57, 229, 184, 0.3); color: var(--secondary-fixed); padding: 4px 8px; font-size: 10px; font-family: var(--font-headline); clip-path: polygon(0 0, calc(100% - 6px) 0, 100% 6px, 100% 100%, 0 100%); font-weight: 700; letter-spacing: 1px; }\n"
    ".nav-title { font-family: var(--font-headline); color: rgba(255,255,255,0.3); font-size: 10px; letter-spacing: 3px; margin-bottom: 16px; border-bottom: 1px dashed rgba(255,255,255,0.1); padding-bottom: 8px; }\n"
    ".nav-list { display: grid; gap: 4px; }\n"
    ".nav-btn { background: transparent; border: none; color: var(--on-primary-container); text-align: left; padding: 12px 16px; cursor: pointer; transition: 0.2s; font-family: var(--font-headline); font-size: 13px; font-weight: 600; letter-spacing: 1px; width: 100%; position: relative; display: flex; flex-direction: column; }\n"
    ".nav-btn .nav-btn-dec { position: absolute; left: 0; top: 0; bottom: 0; width: 3px; background: transparent; transition: 0.2s; }\n"
    ".nav-btn small { font-family: var(--font-body); font-size: 9px; opacity: 0.5; font-weight: 500; margin-top: 4px; letter-spacing: 0; text-transform: uppercase; }\n"
    ".nav-btn:hover { background: rgba(255,255,255,0.02); color: var(--surface-lowest); padding-left: 20px; }\n"
    ".nav-btn:hover .nav-btn-dec { background: rgba(255,255,255,0.2); }\n"
    ".nav-btn.active { background: linear-gradient(90deg, rgba(57, 229, 184, 0.1), transparent); color: var(--secondary-fixed); padding-left: 20px; }\n"
    ".nav-btn.active .nav-btn-dec { background: var(--secondary-fixed); box-shadow: 0 0 10px var(--secondary-fixed); }\n"
    ".nav-btn.active small { color: var(--surface-lowest); opacity: 0.8; }\n"
    ".current { border-top: 1px solid rgba(255,255,255,0.05); padding-top: 24px; margin-top: auto; margin-bottom: 0; }\n"
    ".subtle-label { font-family: var(--font-headline); color: var(--secondary-fixed); font-size: 10px; letter-spacing: 2px; }\n"
    ".current .name { font-family: var(--font-headline); font-size: 18px; font-weight: 700; margin: 8px 0; color: var(--surface-lowest); }\n"
    ".current .helper { font-size: 10px; color: var(--on-primary-container); line-height: 1.6; font-family: var(--font-headline); }\n\n"
    "/* MAIN CONTENT */\n"
    ".main { display: flex; flex-direction: column; position: relative; z-index: 1; }\n"
    "/* 修复割裂感：跨区大阴影 */\n"
    ".main-bridge-shadow { position: absolute; left: 0; top: 0; bottom: 0; width: 120px; background: linear-gradient(90deg, rgba(0,0,0,0.06), transparent); z-index: -1; pointer-events: none; }\n\n"
    ".main-top-bar { height: 24px; border-bottom: 1px solid var(--outline-variant); display: flex; align-items: center; padding: 0 48px; gap: 12px; background: rgba(255,255,255,0.4); }\n"
    ".main-top-bar .line-run { width: 100px; height: 2px; background: var(--secondary-fixed); box-shadow: 0 0 8px var(--secondary-fixed); }\n"
    ".main-top-bar span { font-family: var(--font-headline); font-size: 9px; color: var(--outline); letter-spacing: 2px; font-weight: 700; }\n"
    "\n"
    "/* Hero 注入重量感：深色科技背景 */\n"
    ".hero { background: var(--primary-container); color: var(--surface-lowest); padding: 40px 48px; display: flex; justify-content: space-between; align-items: flex-end; position: relative; z-index: 2; overflow: hidden; }\n"
    ".hero-tech-bg { position: absolute; inset: 0; background: repeating-linear-gradient(45deg, rgba(255,255,255,0.02) 0, rgba(255,255,255,0.02) 2px, transparent 2px, transparent 8px); pointer-events: none; }\n"
    ".hero-content { position: relative; z-index: 2; }\n"
    ".hero .kicker { font-family: var(--font-headline); font-size: 10px; color: var(--secondary-fixed); letter-spacing: 3px; margin-bottom: 12px; font-weight: 700; }\n"
    ".hero h1 { font-family: var(--font-headline); font-size: 36px; font-weight: 900; color: #ffffff; line-height: 1; letter-spacing: -1px; }\n"
    ".hero p { font-size: 13px; color: var(--on-primary-container); margin-top: 12px; max-width: 600px; line-height: 1.6; font-weight: 500; }\n\n"
    ".toolbar { display: flex; gap: 12px; position: relative; z-index: 2; }\n"
    ".toolbar-btn { font-family: var(--font-headline); font-size: 12px; font-weight: 700; padding: 0 24px; height: 42px; display: inline-flex; align-items: center; justify-content: center; gap: 8px; cursor: pointer; letter-spacing: 1px; transition: 0.2s; border: 1px solid rgba(255,255,255,0.2); background: rgba(0,0,0,0.3); color: #ffffff; position: relative; backdrop-filter: blur(4px); }\n"
    ".toolbar-btn:hover { background: rgba(255,255,255,0.1); border-color: var(--secondary-fixed); }\n"
    ".toolbar-btn .btn-icon { font-size: 14px; }\n"
    ".save-btn { background: var(--secondary-fixed); color: var(--on-secondary-fixed); border-color: var(--secondary-fixed); }\n"
    ".save-btn .btn-dec { color: var(--on-secondary-fixed); font-weight: 900; opacity: 0.6; }\n"
    ".save-btn:hover { background: #ffffff; color: var(--primary-container); box-shadow: 0 0 20px var(--secondary-glow); }\n\n"
    ".clip-bevel { clip-path: polygon(10px 0, 100% 0, 100% calc(100% - 10px), calc(100% - 10px) 100%, 0 100%, 0 10px); }\n"
    ".clip-bevel-card { clip-path: polygon(16px 0, 100% 0, 100% calc(100% - 16px), calc(100% - 16px) 100%, 0 100%, 0 16px); }\n"
    ".tactical-corners::before, .tactical-corners::after { content: ''; position: absolute; width: 6px; height: 6px; border: 2px solid var(--secondary-fixed); pointer-events: none; }\n"
    ".tactical-corners::before { top: -1px; left: -1px; border-right: none; border-bottom: none; }\n"
    ".tactical-corners::after { bottom: -1px; right: -1px; border-left: none; border-top: none; }\n"
    ".tactical-corners-lg::before, .tactical-corners-lg::after { content: ''; position: absolute; width: 12px; height: 12px; border: 3px solid var(--primary-container); pointer-events: none; }\n"
    ".tactical-corners-lg::before { top: -1px; left: -1px; border-right: none; border-bottom: none; }\n"
    ".tactical-corners-lg::after { bottom: -1px; right: -1px; border-left: none; border-top: none; }\n\n"
    ".pages { padding: 32px 48px; position: relative; z-index: 2; flex: 1; }\n"
    ".page { display: none; gap: 24px; }\n"
    ".page.active { display: grid; }\n"
    ".grid { display: grid; grid-template-columns: repeat(12, minmax(0,1fr)); gap: 24px; }\n"
    ".col-12 { grid-column: span 12; } .col-8 { grid-column: span 8; } .col-7 { grid-column: span 7; } .col-6 { grid-column: span 6; } .col-5 { grid-column: span 5; } .col-4 { grid-column: span 4; }\n\n"
    ".panel { background: rgba(255,255,255,0.85); backdrop-filter: blur(12px); border: 1px solid var(--outline-variant); padding: 24px; position: relative; box-shadow: 0 4px 16px rgba(0,0,0,0.03); }\n"
    ".panel-head { border-bottom: 2px solid var(--primary-container); padding-bottom: 12px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-start; }\n"
    ".panel-title { font-family: var(--font-headline); font-size: 20px; font-weight: 800; color: var(--primary-container); text-transform: uppercase; display: flex; align-items: center; gap: 8px; }\n"
    ".panel-title::before { content: '>_'; color: var(--secondary-fixed); font-weight: 900; }\n"
    ".panel-note { font-size: 12px; color: var(--on-surface-variant); margin-top: 8px; line-height: 1.6; }\n\n"
    ".input, .textarea, .select { width: 100%; border: none; border-bottom: 2px solid var(--outline); background: rgba(255,255,255,0.5); color: var(--on-surface); padding: 12px 16px; outline: none; font-family: var(--font-body); font-size: 13px; transition: 0.2s; font-weight: 500; }\n"
    ".textarea { min-height: 100px; resize: vertical; }\n"
    ".input:focus, .textarea:focus, .select:focus { border-bottom-color: var(--primary-container); background: rgba(57, 229, 184, 0.05); }\n"
    ".field { display: grid; gap: 8px; }\n"
    ".field label { font-family: var(--font-headline); font-size: 11px; font-weight: 800; color: var(--outline); letter-spacing: 1px; text-transform: uppercase; display: flex; justify-content: space-between; }\n"
    ".field-grid { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 16px; }\n"
    ".field-grid.three { grid-template-columns: repeat(3, minmax(0,1fr)); }\n"
    ".field-grid.four { grid-template-columns: repeat(4, minmax(0,1fr)); }\n\n"
    ".btn, .btn-strong, .btn-danger, .btn-mini, .mode-btn { font-family: var(--font-headline); font-size: 11px; font-weight: 700; padding: 10px 16px; cursor: pointer; letter-spacing: 1px; transition: 0.2s; border: 1px solid var(--outline-variant); background: var(--surface-lowest); color: var(--primary-container); display: inline-flex; justify-content: center; align-items: center; text-transform: uppercase; }\n"
    ".btn:hover { background: var(--surface-high); border-color: var(--primary-container); }\n"
    ".btn-strong { background: var(--primary-container); color: var(--surface-lowest); border-color: var(--primary-container); }\n"
    ".btn-strong:hover { background: var(--secondary-fixed); color: var(--on-secondary-fixed); border-color: var(--secondary-fixed); box-shadow: 0 0 12px var(--secondary-glow); }\n"
    ".btn-danger { color: var(--danger); border-color: rgba(217, 56, 41, 0.3); }\n"
    ".btn-danger:hover { background: var(--danger); color: white; border-color: var(--danger); box-shadow: 0 0 12px var(--danger-glow); }\n\n"
    ".stack { display: grid; gap: 12px; }\n"
    ".row { display: flex; flex-wrap: wrap; gap: 12px; align-items: center; }\n"
    ".profile-card, .event-item, .effect-row { background: var(--surface-lowest); border: 1px solid var(--outline-variant); padding: 16px 20px; transition: 0.2s; position: relative; }\n"
    ".profile-card:hover { border-color: var(--primary-container); transform: translateY(-2px); box-shadow: 0 8px 24px rgba(0,0,0,0.05); }\n"
    ".profile-card.active { border-color: var(--primary-container); box-shadow: inset 4px 0 0 var(--secondary-fixed); background: linear-gradient(90deg, rgba(57, 229, 184, 0.05), transparent); }\n"
    ".profile-card h3 { font-family: var(--font-headline); font-size: 18px; font-weight: 800; color: var(--primary-container); margin-bottom: 6px; letter-spacing: -0.5px; }\n"
    ".profile-card .meta, .profile-card .helper { font-size: 12px; color: var(--on-surface-variant); margin-bottom: 12px; font-weight: 500; }\n"
    ".badge { display: inline-flex; padding: 4px 8px; font-family: var(--font-headline); font-size: 10px; font-weight: 700; letter-spacing: 1px; background: var(--surface-high); color: var(--on-surface); border: 1px solid var(--outline-variant); }\n\n"
    ".toggle-row { display: flex; justify-content: space-between; align-items: flex-start; padding: 16px; border: 1px solid var(--outline-variant); background: var(--surface-lowest); margin-bottom: 12px; transition: 0.2s; }\n"
    ".toggle-row:hover { border-color: var(--outline); }\n"
    ".toggle-copy .helper { font-size: 12px; color: var(--on-surface-variant); margin-top: 6px; line-height: 1.5; }\n"
    ".toggle-box { width: 48px; height: 26px; background: var(--surface-high); border: 1px solid var(--outline-variant); position: relative; cursor: pointer; transition: 0.2s; flex-shrink: 0; box-shadow: inset 0 2px 4px rgba(0,0,0,0.05); }\n"
    ".toggle-box::before { content: ''; position: absolute; left: 2px; top: 2px; width: 20px; height: 20px; background: var(--outline); transition: 0.2s; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }\n"
    ".toggle-box.on { background: var(--primary-container); border-color: var(--primary-container); }\n"
    ".toggle-box.on::before { transform: translateX(22px); background: var(--secondary-fixed); box-shadow: 0 0 8px var(--secondary-fixed); }\n\n"
    ".archive-grid, .pending-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 20px; }\n"
    ".archive-card { background: var(--surface-lowest); border: 1px solid var(--outline-variant); display: flex; flex-direction: column; transition: 0.3s; position: relative; isolation: isolate; }\n"
    ".archive-card::before { content: ''; position: absolute; left: 0; top: 0; right: 0; height: 4px; background: var(--outline-variant); z-index: 2; transition: 0.3s; }\n"
    ".archive-card:hover { transform: translateY(-4px); box-shadow: 0 12px 32px rgba(0,0,0,0.08); border-color: var(--primary-container); }\n"
    ".archive-card:hover::before { background: var(--secondary-fixed); box-shadow: 0 2px 10px var(--secondary-glow); }\n"
    ".archive-cover { aspect-ratio: 3/4; background: linear-gradient(135deg, var(--surface-low), var(--surface-high)); border-bottom: 1px solid var(--outline-variant); padding: 12px; display: flex; align-items: center; justify-content: center; overflow: hidden; position: relative; }\n"
    ".archive-cover::after { content: '[ IMG_SLOT ]'; position: absolute; font-family: var(--font-headline); font-size: 10px; font-weight: 700; color: rgba(0,0,0,0.1); letter-spacing: 2px; z-index: 0; }\n"
    ".archive-cover img { width: 100%; height: 100%; object-fit: cover; border: 1px solid var(--outline-variant); z-index: 1; position: relative; }\n"
    ".archive-body { padding: 16px; display: flex; flex-direction: column; gap: 8px; flex: 1; }\n"
    ".archive-title { font-family: var(--font-headline); font-size: 16px; font-weight: 800; color: var(--primary-container); }\n"
    ".archive-desc { font-size: 12px; color: var(--on-surface-variant); background: var(--surface-low); padding: 12px; border: 1px solid var(--outline-variant); border-left: 3px solid var(--outline); line-height: 1.5; }\n"
    ".archive-actions { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-top: auto; padding-top: 16px; border-top: 1px dashed var(--outline-variant); }\n"
    ".archive-actions .btn { padding: 8px 0; font-size: 10px; text-align: center; }\n\n"
    ".overview-stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-top: 24px; }\n"
    ".overview-stat { border: 1px solid var(--outline-variant); background: linear-gradient(180deg, var(--surface-lowest), var(--surface-low)); padding: 20px; border-left: 4px solid var(--secondary-fixed); position: relative; }\n"
    ".overview-stat::after { content: ''; position: absolute; right: 20px; top: 20px; width: 16px; height: 16px; border: 2px solid var(--outline-variant); border-radius: 50% !important; }\n"
    ".overview-stat b { font-family: var(--font-headline); font-size: 32px; font-weight: 900; color: var(--primary-container); display: block; margin-bottom: 4px; letter-spacing: -1px; }\n"
    ".overview-stat span { font-size: 11px; color: var(--outline); text-transform: uppercase; letter-spacing: 2px; font-weight: 700; font-family: var(--font-headline); display: block; }\n\n"
    ".dialog { position: fixed; inset: 0; background: rgba(17, 29, 21, 0.85); backdrop-filter: blur(8px); z-index: 100; display: none; align-items: center; justify-content: center; padding: 24px; }\n"
    ".dialog.show { display: flex; }\n"
    ".dialog-card { background: var(--surface-lowest); border: 2px solid var(--primary-container); width: min(1000px, 100%); max-height: 90vh; overflow-y: auto; padding: 40px; box-shadow: 0 32px 80px rgba(0,0,0,0.3); position: relative; }\n"
    ".dialog-head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid var(--primary-container); padding-bottom: 16px; margin-bottom: 32px; }\n"
    ".dialog-title { font-family: var(--font-headline); font-size: 24px; font-weight: 900; color: var(--primary-container); text-transform: uppercase; }\n"
    ".tiny { font-family: var(--font-headline); font-size: 11px; color: var(--outline); letter-spacing: 3px; margin-bottom: 4px; font-weight: 700; }\n\n"
    ".toast { position: fixed; right: 32px; bottom: 32px; background: var(--primary-container); color: var(--surface-lowest); padding: 16px 24px; font-family: var(--font-body); font-size: 13px; font-weight: 600; z-index: 200; box-shadow: 0 16px 40px rgba(0,0,0,0.2); opacity: 0; transform: translateY(20px); transition: 0.3s; border-left: 4px solid var(--secondary-fixed); letter-spacing: 0.5px; }\n"
    ".toast.show { opacity: 1; transform: translateY(0); }\n"
    ".toast.bad { border-left-color: var(--danger); }\n\n"
    "/* Dynamic Elements overrides */\n"
    ".thumb { width: 80px; height: 80px; border: 1px solid var(--outline-variant); background: var(--surface-low); overflow: hidden; display: flex; align-items: center; justify-content: center; }\n"
    ".thumb img { width: 100%; height: 100%; object-fit: cover; }\n"
    ".asset-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }\n"
    ".tag-preview, .empty { background: rgba(255,255,255,0.5); border: 1px dashed var(--outline); padding: 24px; text-align: center; font-size: 13px; color: var(--on-surface-variant); font-weight: 500; }\n"
    ".filter-bar { display: flex; gap: 16px; align-items: center; padding: 16px; background: var(--surface-lowest); border: 1px solid var(--outline-variant); margin-bottom: 20px; }\n"
    ".stats-profile-bar { border-bottom: 2px solid var(--outline-variant); padding-bottom: 16px; margin-bottom: 24px; }\n"
    ".stats-kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; }\n"
    ".stats-kpi { border: 1px solid var(--outline-variant); background: linear-gradient(135deg, var(--surface-lowest), var(--surface-low)); padding: 20px; border-left: 4px solid var(--primary-container); position: relative; }\n"
    ".group-entry, .leaderboard-item { border: 1px solid var(--outline-variant); background: var(--surface-lowest); padding: 16px; margin-bottom: 12px; transition: 0.2s; }\n"
    ".group-entry:hover, .leaderboard-item:hover { border-color: var(--outline); transform: translateX(4px); }\n"
    ".pool-card { border: 1px solid var(--outline-variant); background: var(--surface-lowest); padding: 24px; border-top: 4px solid var(--primary-container); box-shadow: 0 8px 24px rgba(0,0,0,0.02); }\n"
    "\n"
    "::-webkit-scrollbar { width: 8px; height: 8px; }\n"
    "::-webkit-scrollbar-track { background: var(--surface-low); border-left: 1px solid var(--outline-variant); }\n"
    "::-webkit-scrollbar-thumb { background: var(--outline); }\n"
    "::-webkit-scrollbar-thumb:hover { background: var(--primary-container); }\n"
)

with open('webui/static/styles.css', 'w', encoding='utf-8') as f:
    f.write(css_code)
print('CSS layout fixed.')
