css_code = (
    "@charset 'UTF-8';\n\n"
    ":root {\n"
    "  --primary-container: #1b3022;\n"
    "  --on-primary-container: #8eab97;\n"
    "  --secondary-fixed: #5FF2D0;\n"
    "  --on-secondary-fixed: #002019;\n"
    "  --surface-lowest: #ffffff;\n"
    "  --surface-low: #f4f6f5;\n"
    "  --surface-high: #e2e8e4;\n"
    "  --on-surface: #191c1c;\n"
    "  --on-surface-variant: #434843;\n"
    "  --outline: #737973;\n"
    "  --outline-variant: #ced4d0;\n"
    "  --danger: #ba1a1a;\n"
    "  --font-headline: 'Space Grotesk', 'Source Han Sans SC', sans-serif;\n"
    "  --font-body: 'Inter', 'Source Han Sans SC', sans-serif;\n"
    "}\n\n"
    "* { box-sizing: border-box; margin: 0; padding: 0; border-radius: 0 !important; }\n\n"
    "html, body { min-height: 100%; color-scheme: light; }\n"
    "body { font-family: var(--font-body); color: var(--on-surface); background-color: var(--surface-low); }\n\n"
    "/* Background Grid */\n"
    "body::before { content: ''; position: fixed; inset: 0; pointer-events: none; background: linear-gradient(var(--outline-variant) 1px, transparent 1px), linear-gradient(90deg, var(--outline-variant) 1px, transparent 1px); background-size: 40px 40px; opacity: 0.15; z-index: -1; }\n\n"
    "/* Base Layout */\n"
    ".app { display: grid; grid-template-columns: 240px minmax(0, 1fr); min-height: 100vh; }\n\n"
    "/* SIDEBAR */\n"
    ".side { background: var(--primary-container); color: var(--surface-lowest); display: flex; flex-direction: column; z-index: 10; padding: 32px 0; }\n"
    ".block { padding: 0 20px; margin-bottom: 32px; border:none; background:transparent; box-shadow:none; }\n"
    ".brand .mini { font-family: var(--font-headline); color: var(--secondary-fixed); letter-spacing: 2px; font-size: 10px; margin-bottom: 12px; }\n"
    ".brand .big { font-family: var(--font-headline); font-size: 38px; font-weight: 900; line-height: 1; color: var(--surface-lowest); }\n"
    ".chip { background: rgba(255,255,255,0.05); border: 1px solid rgba(255,255,255,0.1); color: var(--secondary-fixed); padding: 4px 8px; font-size: 10px; font-family: var(--font-headline); clip-path: polygon(0 0, calc(100% - 6px) 0, 100% 6px, 100% 100%, 0 100%); }\n\n"
    ".nav-title { font-family: var(--font-headline); color: var(--on-primary-container); font-size: 10px; letter-spacing: 2px; margin-bottom: 16px; }\n"
    ".nav-list { display: grid; gap: 4px; }\n"
    ".nav-btn { background: transparent; border: none; color: var(--on-primary-container); text-align: left; padding: 12px 16px; cursor: pointer; font-family: var(--font-headline); font-size: 12px; font-weight: 600; transition:0.2s; }\n"
    ".nav-btn small { display: block; font-family: var(--font-body); font-size: 10px; opacity: 0.6; font-weight: 400; margin-top: 4px; }\n"
    ".nav-btn:hover { background: rgba(255,255,255,0.03); color: var(--surface-lowest); border-left: 3px solid var(--secondary-fixed); padding-left: 19px; }\n"
    ".nav-btn.active { background: var(--secondary-fixed); color: var(--on-secondary-fixed); clip-path: polygon(10px 0, 100% 0, 100% calc(100% - 10px), calc(100% - 10px) 100%, 0 100%, 0 10px); padding-left: 16px; }\n"
    ".nav-btn.active small { color: var(--on-secondary-fixed); opacity: 0.8; }\n\n"
    ".current { border-top: 1px solid rgba(255,255,255,0.05); padding-top: 24px; margin-top: auto; }\n"
    ".subtle-label { font-family: var(--font-headline); color: var(--secondary-fixed); font-size: 10px; letter-spacing: 2px; }\n"
    ".current .name { font-family: var(--font-headline); font-size: 18px; font-weight: 700; margin: 8px 0; color: var(--surface-lowest); }\n"
    ".current .helper { font-size: 11px; color: var(--on-primary-container); }\n\n"
    "/* MAIN CONTENT */\n"
    ".main { display: flex; flex-direction: column; background: var(--surface-low); }\n"
    ".hero { background: var(--surface-lowest); padding: 32px 48px; border-bottom: 1px solid var(--outline-variant); display: flex; justify-content: space-between; align-items: flex-end; position: relative; }\n"
    ".hero::after { content: ''; position: absolute; left: 0; bottom: -1px; width: 120px; height: 3px; background: var(--primary-container); }\n"
    ".hero .kicker { font-family: var(--font-headline); font-size: 10px; color: var(--outline); letter-spacing: 2px; margin-bottom: 12px; }\n"
    ".hero h1 { font-family: var(--font-headline); font-size: 32px; font-weight: 900; color: var(--primary-container); }\n"
    ".hero p { font-size: 13px; color: var(--on-surface-variant); margin-top: 12px; }\n\n"
    ".toolbar { display: flex; gap: 12px; }\n"
    ".toolbar-btn { font-family: var(--font-headline); font-size: 11px; font-weight: 700; padding: 0 20px; height: 38px; cursor: pointer; border: 1px solid var(--outline-variant); background: var(--surface-lowest); color: var(--primary-container); }\n"
    ".toolbar-btn:hover { background: var(--surface-low); border-color: var(--primary-container); }\n"
    ".save-btn { background: var(--primary-container); color: var(--surface-lowest); border: none; }\n"
    ".save-btn:hover { background: var(--secondary-fixed); color: var(--on-secondary-fixed); }\n\n"
    "/* Utilities */\n"
    ".clip-bevel { clip-path: polygon(8px 0, 100% 0, 100% calc(100% - 8px), calc(100% - 8px) 100%, 0 100%, 0 8px); }\n"
    ".clip-bevel-card { clip-path: polygon(12px 0, 100% 0, 100% calc(100% - 12px), calc(100% - 12px) 100%, 0 100%, 0 12px); }\n\n"
    "/* Grid & Pages */\n"
    ".pages { padding: 32px 48px; flex: 1; }\n"
    ".page { display: none; gap: 24px; }\n"
    ".page.active { display: grid; }\n"
    ".grid { display: grid; grid-template-columns: repeat(12, minmax(0,1fr)); gap: 20px; }\n"
    ".col-12 { grid-column: span 12; } .col-8 { grid-column: span 8; } .col-6 { grid-column: span 6; } .col-4 { grid-column: span 4; }\n\n"
    "/* Panels */\n"
    ".panel { background: var(--surface-lowest); border: 1px solid var(--outline-variant); padding: 24px; }\n"
    ".panel-head { border-bottom: 2px solid var(--on-surface); padding-bottom: 12px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: flex-start; }\n"
    ".panel-title { font-family: var(--font-headline); font-size: 18px; font-weight: 800; color: var(--on-surface); }\n"
    ".panel-note { font-size: 12px; color: var(--on-surface-variant); margin-top: 8px; }\n\n"
    "/* Inputs */\n"
    ".input, .textarea, .select { width: 100%; border: none; border-bottom: 2px solid var(--outline); background: var(--surface-low); padding: 10px 14px; outline: none; font-size: 13px; }\n"
    ".input:focus, .textarea:focus, .select:focus { border-bottom-color: var(--secondary-fixed); background: #ebfcf8; }\n"
    ".textarea { min-height: 100px; resize: vertical; }\n"
    ".field { display: grid; gap: 8px; }\n"
    ".field label { font-family: var(--font-headline); font-size: 10px; font-weight: 700; color: var(--outline); }\n"
    ".field-grid { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 16px; }\n\n"
    "/* Buttons */\n"
    ".btn, .btn-strong, .btn-danger, .btn-mini, .mode-btn { font-family: var(--font-headline); font-size: 11px; font-weight: 700; padding: 10px 16px; cursor: pointer; border: 1px solid var(--outline-variant); background: var(--surface-lowest); color: var(--primary-container); }\n"
    ".btn:hover { background: var(--surface-low); border-color: var(--primary-container); }\n"
    ".btn-strong { background: var(--primary-container); color: var(--surface-lowest); border-color: var(--primary-container); clip-path: polygon(8px 0, 100% 0, 100% calc(100% - 8px), calc(100% - 8px) 100%, 0 100%, 0 8px); }\n"
    ".btn-strong:hover { background: var(--secondary-fixed); color: var(--on-secondary-fixed); border-color: var(--secondary-fixed); }\n"
    ".btn-danger { color: var(--danger); }\n"
    ".btn-danger:hover { background: var(--danger); color: white; }\n\n"
    "/* Cards & Lists */\n"
    ".stack { display: grid; gap: 12px; }\n"
    ".row { display: flex; flex-wrap: wrap; gap: 10px; }\n"
    ".profile-card, .event-item, .effect-row { background: var(--surface-lowest); border: 1px solid var(--outline-variant); padding: 16px 20px; }\n"
    ".profile-card:hover { border-color: var(--outline); transform: translateY(-1px); }\n"
    ".profile-card.active { border-color: var(--primary-container); border-left: 4px solid var(--primary-container); }\n"
    ".profile-card h3 { font-family: var(--font-headline); font-size: 16px; font-weight: 800; color: var(--primary-container); }\n"
    ".badge { padding: 4px 8px; font-family: var(--font-headline); font-size: 10px; font-weight: 700; background: var(--surface-low); border: 1px solid var(--outline-variant); }\n\n"
    "/* Toggles */\n"
    ".toggle-row { display: flex; justify-content: space-between; padding: 16px; border: 1px solid var(--outline-variant); background: var(--surface-lowest); margin-bottom: 8px; }\n"
    ".toggle-box { width: 44px; height: 24px; background: var(--surface-low); border: 1px solid var(--outline-variant); position: relative; cursor: pointer; }\n"
    ".toggle-box::before { content: ''; position: absolute; left: 2px; top: 2px; width: 18px; height: 18px; background: var(--outline); transition: 0.2s; }\n"
    ".toggle-box.on { background: var(--primary-container); border-color: var(--primary-container); }\n"
    ".toggle-box.on::before { transform: translateX(20px); background: var(--secondary-fixed); }\n\n"
    "/* Archive Grids (Cards/Fate) */\n"
    ".archive-grid, .pending-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 16px; }\n"
    ".archive-card { background: var(--surface-lowest); border: 1px solid var(--outline-variant); display: flex; flex-direction: column; position: relative; }\n"
    ".archive-card::before { content: ''; position: absolute; left: 0; top: 0; right: 0; height: 3px; background: var(--outline-variant); transition: 0.2s; }\n"
    ".archive-card:hover { transform: translateY(-2px); border-color: var(--primary-container); }\n"
    ".archive-card:hover::before { background: var(--secondary-fixed); }\n"
    ".archive-cover { aspect-ratio: 3/4; background: var(--surface-low); border-bottom: 1px solid var(--outline-variant); padding: 12px; display: flex; align-items: center; justify-content: center; overflow: hidden; }\n"
    ".archive-cover img { width: 100%; height: 100%; object-fit: cover; border: 1px solid var(--outline-variant); }\n"
    ".archive-body { padding: 16px; display: flex; flex-direction: column; gap: 8px; flex: 1; }\n"
    ".archive-title { font-family: var(--font-headline); font-size: 15px; font-weight: 800; color: var(--primary-container); }\n"
    ".archive-desc { font-size: 12px; color: var(--on-surface-variant); background: var(--surface-low); padding: 10px; border: 1px solid var(--outline-variant); border-left: 2px solid var(--outline); }\n"
    ".archive-actions { display: grid; grid-template-columns: repeat(3, 1fr); gap: 8px; margin-top: auto; padding-top: 12px; border-top: 1px solid var(--outline-variant); }\n"
    ".archive-actions .btn { padding: 8px 0; font-size: 10px; }\n\n"
    "/* Dialog */\n"
    ".dialog { position: fixed; inset: 0; background: rgba(25, 28, 28, 0.6); backdrop-filter: blur(4px); z-index: 100; display: none; align-items: center; justify-content: center; padding: 24px; }\n"
    ".dialog.show { display: flex; }\n"
    ".dialog-card { background: var(--surface-lowest); border: 1px solid var(--primary-container); width: min(1000px, 100%); max-height: 90vh; overflow-y: auto; padding: 32px; box-shadow: 0 24px 64px rgba(0,0,0,0.1); }\n"
    ".dialog-head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid var(--on-surface); padding-bottom: 16px; margin-bottom: 24px; }\n"
    ".dialog-title { font-family: var(--font-headline); font-size: 20px; font-weight: 900; color: var(--primary-container); }\n\n"
    "/* Toast */\n"
    ".toast { position: fixed; right: 32px; bottom: 32px; background: var(--primary-container); color: var(--surface-lowest); padding: 16px 24px; font-size: 13px; z-index: 200; opacity: 0; transform: translateY(20px); transition: 0.3s; border-left: 4px solid var(--secondary-fixed); }\n"
    ".toast.show { opacity: 1; transform: translateY(0); }\n"
    ".toast.bad { border-left-color: var(--danger); }\n\n"
    "/* Overrides for dynamic elements */\n"
    ".thumb { width: 80px; height: 80px; border: 1px solid var(--outline-variant); background: var(--surface-low); display: flex; align-items: center; justify-content: center; }\n"
    ".thumb img { width: 100%; height: 100%; object-fit: cover; }\n"
    ".asset-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; }\n"
    ".tag-preview, .empty { background: var(--surface-low); border: 1px dashed var(--outline-variant); padding: 20px; text-align: center; font-size: 12px; color: var(--on-surface-variant); }\n"
    ".overview-stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-top: 24px; }\n"
    ".overview-stat { border: 1px solid var(--outline-variant); background: var(--surface-lowest); padding: 16px; border-left: 3px solid var(--secondary-fixed); }\n"
    ".overview-stat b { font-family: var(--font-headline); font-size: 24px; font-weight: 900; color: var(--primary-container); display: block; }\n"
    ".overview-stat span { font-size: 10px; color: var(--outline); font-family: var(--font-headline); }\n"
)

with open('webui/static/styles.css', 'w', encoding='utf-8') as f:
    f.write(css_code)

print('CSS written safely.')
