app_html = (
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>武陵战术数据中枢 - WULING</title>\n"
    "  <link href=\"https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700;900&family=Inter:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\n"
    "  <link rel=\"stylesheet\" href=\"/static/styles.css\">\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"app\">\n"
    "    <aside class=\"side\">\n"
    "      <!-- Top tactical decorations -->\n"
    "      <div class=\"side-top-dec\">\n"
    "        <div class=\"blink-dot\"></div>\n"
    "        <span>SYS.OP.NOMINAL // UPLINK SECURE</span>\n"
    "      </div>\n\n"
    "      <section class=\"block brand\">\n"
    "        <div class=\"mini\">[ ENDFIELD_WULING ARCHIVE ]</div>\n"
    "        <div class=\"big-wrap\">\n"
    "          <div class=\"big\">武陵<br>中枢</div>\n"
    "        </div>\n"
    "        <div class=\"row\">\n"
    "          <span class=\"chip\">Ver. 5.4.0</span>\n"
    "          <span class=\"chip\">[ CORE_TERMINAL ]</span>\n"
    "        </div>\n"
    "      </section>\n\n"
    "      <section class=\"block nav\">\n"
    "        <div class=\"nav-title\">[ SEC_INDEX ]</div>\n"
    "        <div class=\"nav-list\">\n"
    "          <button class=\"nav-btn active\" data-page=\"overview\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            总览与方案<small>PROFILE / ACCESS</small>\n"
    "          </button>\n"
    "          <button class=\"nav-btn\" data-page=\"runtime\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            运行配置<small>RUNTIME / PROBABILITY</small>\n"
    "          </button>\n"
    "          <button class=\"nav-btn\" data-page=\"signin\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            签到配置<small>SIGN_IN / FORECAST</small>\n"
    "          </button>\n"
    "          <button class=\"nav-btn\" data-page=\"fate\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            命运牌档案<small>FATE_MATRIX / ASSETS</small>\n"
    "          </button>\n"
    "          <button class=\"nav-btn\" data-page=\"cards\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            功能牌档案<small>FUNC_CARDS / EFFECTS</small>\n"
    "          </button>\n"
    "          <button class=\"nav-btn\" data-page=\"titles\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            称号档案<small>TITLES / CONDITIONS</small>\n"
    "          </button>\n"
    "          <button class=\"nav-btn\" data-page=\"stats\">\n"
    "            <div class=\"nav-btn-dec\"></div>\n"
    "            数据统计<small>DATA_STATS / RANKS</small>\n"
    "          </button>\n"
    "        </div>\n"
    "      </section>\n\n"
    "      <section class=\"block current\">\n"
    "        <div class=\"subtle-label\">[ ACTIVE_PROFILE ]</div>\n"
    "        <div class=\"name\" id=\"currentProfileName\">加载中...</div>\n"
    "        <div class=\"helper\">GLOBAL_SYNC // 全局参数自动跟随当前活跃方案同步。</div>\n"
    "      </section>\n"
    "      <div class=\"side-edge\"></div>\n"
    "      <div class=\"side-bottom-dec\">\n"
    "         <span>WULING_TECH_SYS // 2026.0</span>\n"
    "      </div>\n"
    "    </aside>\n\n"
    "    <main class=\"main\">\n"
    "      <div class=\"main-top-bar\">\n"
    "         <div class=\"line-run\"></div>\n"
    "         <span>DATA_STREAM_ACTIVE /// LOCATION: LOCALHOST</span>\n"
    "      </div>\n\n"
    "      <section class=\"hero\">\n"
    "        <div>\n"
    "          <div class=\"kicker\">[ TERRA WEB UI / ARCHIVE CONTROL ]</div>\n"
    "          <h1 id=\"heroTitle\">总览与方案</h1>\n"
    "          <p id=\"heroDesc\">管理活跃协议配置与群组访问权限。</p>\n"
    "        </div>\n"
    "        <div class=\"hero-side\">\n"
    "          <div class=\"hero-aux\" id=\"heroAux\"></div>\n"
    "          <div class=\"toolbar\">\n"
    "            <button class=\"btn toolbar-btn refresh-btn tactical-corners\" id=\"reloadBtn\">\n"
    "                <span class=\"btn-icon\">↻</span> RELOAD\n"
    "            </button>\n"
    "            <button class=\"btn btn-strong toolbar-btn save-btn clip-bevel\" id=\"saveAllBtn\">\n"
    "                SAVE_SYNC <span class=\"btn-dec\">+</span>\n"
    "            </button>\n"
    "          </div>\n"
    "        </div>\n"
    "      </section>\n\n"
    "      <section class=\"pages\">\n"
    "        <div class=\"page active\" id=\"page-overview\"></div>\n"
    "        <div class=\"page\" id=\"page-runtime\"></div>\n"
    "        <div class=\"page\" id=\"page-signin\"></div>\n"
    "        <div class=\"page\" id=\"page-fate\"></div>\n"
    "        <div class=\"page\" id=\"page-cards\"></div>\n"
    "        <div class=\"page\" id=\"page-titles\"></div>\n"
    "        <div class=\"page\" id=\"page-stats\"></div>\n"
    "      </section>\n"
    "    </main>\n"
    "  </div>\n\n"
    "  <div class=\"dialog\" id=\"dialog\">\n"
    "    <div class=\"dialog-card clip-bevel-card tactical-corners-lg\">\n"
    "      <div class=\"dialog-head\">\n"
    "        <div>\n"
    "          <div class=\"tiny\">[ TERMINAL_EDITOR ]</div>\n"
    "          <div class=\"dialog-title\" id=\"dialogTitle\">编辑器</div>\n"
    "        </div>\n"
    "        <button class=\"btn tactical-corners\" id=\"closeDialogBtn\">[ CLOSE ]</button>\n"
    "      </div>\n"
    "      <div id=\"dialogBody\"></div>\n"
    "    </div>\n"
    "  </div>\n\n"
    "  <div class=\"toast clip-bevel\" id=\"toast\"></div>\n\n"
    "  <script src=\"/static/js/main.js\"></script>\n"
    "</body>\n"
    "</html>\n"
)

with open('webui/static/app.html', 'w', encoding='utf-8') as f:
    f.write(app_html)
print('HTML updated')
